### ISSUE TITLE
Can't install `pip install jctconv`

### ISSUE THREAD

**Issue by chezou** [ikegami-yukino/jctconv#3]
I tried to install via pip, but I failed installing  jctconv.

``` shell
~/s/JapaneseTokenizers ❯❯❯ pip install jctconv                                                                                            ⏎ ✱ ◼
Collecting jctconv
  Using cached jctconv-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gc/vtw38ncj07v80xwrxmclpnv00000gn/T/pip-build-gi3lpwlh/jctconv/setup.py", line 42, in <module>
        open('CHANGES.rst', encoding='utf8').read()),
      File "/Users/mic/.pyenv/versions/3.5.0/lib/python3.5/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gc/vtw38ncj07v80xwrxmclpnv00000gn/T/pip-build-gi3lpwlh/jctconv/
```

I downloaded tar.gz from pipy, but it doesn't include `CHANGES.rst`.

**Comment by ikegami-yukino** [comment]
Thanks for reporting bug.

This bug is often occurred when replacing distutils with setuptools.
setuptools is required MANIFEST.in file.
So I added MANIFEST.in file.
And uploading PyPI.

Let's retry it.

**Comment by chezou** [comment]
Thanks for quick fix!
